sudo: required
language: cpp
dist: trusty
compiler:
- g++
os:
- linux
notification:
        email:false
env:
        global:
        - LANG="en_US.UTF-8"
branches:
        only:
        - master
script:
        make && make run